	soc_system u0 (
		.adc_0_external_interface_sclk                   (<connected-to-adc_0_external_interface_sclk>),                   //                 adc_0_external_interface.sclk
		.adc_0_external_interface_cs_n                   (<connected-to-adc_0_external_interface_cs_n>),                   //                                         .cs_n
		.adc_0_external_interface_dout                   (<connected-to-adc_0_external_interface_dout>),                   //                                         .dout
		.adc_0_external_interface_din                    (<connected-to-adc_0_external_interface_din>),                    //                                         .din
		.button_pio_external_connection_export           (<connected-to-button_pio_external_connection_export>),           //           button_pio_external_connection.export
		.clk_clk                                         (<connected-to-clk_clk>),                                         //                                      clk.clk
		.dipsw_pio_external_connection_export            (<connected-to-dipsw_pio_external_connection_export>),            //            dipsw_pio_external_connection.export
		.e_stop_external_connection_export               (<connected-to-e_stop_external_connection_export>),               //               e_stop_external_connection.export
		.gpio_pio_0_external_connection_export           (<connected-to-gpio_pio_0_external_connection_export>),           //           gpio_pio_0_external_connection.export
		.gpio_pio_1_external_connection_export           (<connected-to-gpio_pio_1_external_connection_export>),           //           gpio_pio_1_external_connection.export
		.heartbeat_external_connection_export            (<connected-to-heartbeat_external_connection_export>),            //            heartbeat_external_connection.export
		.hps_0_h2f_reset_reset_n                         (<connected-to-hps_0_h2f_reset_reset_n>),                         //                          hps_0_h2f_reset.reset_n
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK           (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>),           //                             hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),             //                                         .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),             //                                         .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),             //                                         .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),             //                                         .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),             //                                         .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),             //                                         .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC              (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),              //                                         .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL           (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>),           //                                         .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL           (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>),           //                                         .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK           (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>),           //                                         .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),             //                                         .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),             //                                         .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),             //                                         .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_sdio_inst_CMD               (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),               //                                         .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0                (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),                //                                         .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1                (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),                //                                         .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK               (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),               //                                         .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2                (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),                //                                         .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3                (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),                //                                         .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0                (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),                //                                         .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1                (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),                //                                         .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2                (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),                //                                         .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3                (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),                //                                         .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4                (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),                //                                         .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5                (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),                //                                         .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6                (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),                //                                         .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7                (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),                //                                         .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK               (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),               //                                         .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP               (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),               //                                         .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR               (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),               //                                         .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT               (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),               //                                         .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_spim1_inst_CLK              (<connected-to-hps_0_hps_io_hps_io_spim1_inst_CLK>),              //                                         .hps_io_spim1_inst_CLK
		.hps_0_hps_io_hps_io_spim1_inst_MOSI             (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MOSI>),             //                                         .hps_io_spim1_inst_MOSI
		.hps_0_hps_io_hps_io_spim1_inst_MISO             (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MISO>),             //                                         .hps_io_spim1_inst_MISO
		.hps_0_hps_io_hps_io_spim1_inst_SS0              (<connected-to-hps_0_hps_io_hps_io_spim1_inst_SS0>),              //                                         .hps_io_spim1_inst_SS0
		.hps_0_hps_io_hps_io_uart0_inst_RX               (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),               //                                         .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX               (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),               //                                         .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_i2c0_inst_SDA               (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SDA>),               //                                         .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_hps_io_i2c0_inst_SCL               (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SCL>),               //                                         .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_hps_io_i2c1_inst_SDA               (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SDA>),               //                                         .hps_io_i2c1_inst_SDA
		.hps_0_hps_io_hps_io_i2c1_inst_SCL               (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SCL>),               //                                         .hps_io_i2c1_inst_SCL
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09            (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),            //                                         .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35            (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),            //                                         .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO40            (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO40>),            //                                         .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53            (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),            //                                         .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_hps_io_gpio_inst_GPIO54            (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO54>),            //                                         .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_hps_io_gpio_inst_GPIO61            (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO61>),            //                                         .hps_io_gpio_inst_GPIO61
		.led_pio_external_connection_export              (<connected-to-led_pio_external_connection_export>),              //              led_pio_external_connection.export
		.limit_pio_external_connection_export            (<connected-to-limit_pio_external_connection_export>),            //            limit_pio_external_connection.export
		.memory_mem_a                                    (<connected-to-memory_mem_a>),                                    //                                   memory.mem_a
		.memory_mem_ba                                   (<connected-to-memory_mem_ba>),                                   //                                         .mem_ba
		.memory_mem_ck                                   (<connected-to-memory_mem_ck>),                                   //                                         .mem_ck
		.memory_mem_ck_n                                 (<connected-to-memory_mem_ck_n>),                                 //                                         .mem_ck_n
		.memory_mem_cke                                  (<connected-to-memory_mem_cke>),                                  //                                         .mem_cke
		.memory_mem_cs_n                                 (<connected-to-memory_mem_cs_n>),                                 //                                         .mem_cs_n
		.memory_mem_ras_n                                (<connected-to-memory_mem_ras_n>),                                //                                         .mem_ras_n
		.memory_mem_cas_n                                (<connected-to-memory_mem_cas_n>),                                //                                         .mem_cas_n
		.memory_mem_we_n                                 (<connected-to-memory_mem_we_n>),                                 //                                         .mem_we_n
		.memory_mem_reset_n                              (<connected-to-memory_mem_reset_n>),                              //                                         .mem_reset_n
		.memory_mem_dq                                   (<connected-to-memory_mem_dq>),                                   //                                         .mem_dq
		.memory_mem_dqs                                  (<connected-to-memory_mem_dqs>),                                  //                                         .mem_dqs
		.memory_mem_dqs_n                                (<connected-to-memory_mem_dqs_n>),                                //                                         .mem_dqs_n
		.memory_mem_odt                                  (<connected-to-memory_mem_odt>),                                  //                                         .mem_odt
		.memory_mem_dm                                   (<connected-to-memory_mem_dm>),                                   //                                         .mem_dm
		.memory_oct_rzqin                                (<connected-to-memory_oct_rzqin>),                                //                                         .oct_rzqin
		.pid_correction_pio_0_external_connection_export (<connected-to-pid_correction_pio_0_external_connection_export>), // pid_correction_pio_0_external_connection.export
		.pid_correction_pio_1_external_connection_export (<connected-to-pid_correction_pio_1_external_connection_export>), // pid_correction_pio_1_external_connection.export
		.pid_correction_pio_2_external_connection_export (<connected-to-pid_correction_pio_2_external_connection_export>), // pid_correction_pio_2_external_connection.export
		.pid_correction_pio_3_external_connection_export (<connected-to-pid_correction_pio_3_external_connection_export>), // pid_correction_pio_3_external_connection.export
		.pid_correction_pio_4_external_connection_export (<connected-to-pid_correction_pio_4_external_connection_export>), // pid_correction_pio_4_external_connection.export
		.pid_correction_pio_5_external_connection_export (<connected-to-pid_correction_pio_5_external_connection_export>), // pid_correction_pio_5_external_connection.export
		.pid_correction_pio_6_external_connection_export (<connected-to-pid_correction_pio_6_external_connection_export>), // pid_correction_pio_6_external_connection.export
		.pid_correction_pio_7_external_connection_export (<connected-to-pid_correction_pio_7_external_connection_export>), // pid_correction_pio_7_external_connection.export
		.pid_error_pio_0_external_connection_export      (<connected-to-pid_error_pio_0_external_connection_export>),      //      pid_error_pio_0_external_connection.export
		.pid_error_pio_1_external_connection_export      (<connected-to-pid_error_pio_1_external_connection_export>),      //      pid_error_pio_1_external_connection.export
		.pid_error_pio_2_external_connection_export      (<connected-to-pid_error_pio_2_external_connection_export>),      //      pid_error_pio_2_external_connection.export
		.pid_error_pio_3_external_connection_export      (<connected-to-pid_error_pio_3_external_connection_export>),      //      pid_error_pio_3_external_connection.export
		.pid_error_pio_4_external_connection_export      (<connected-to-pid_error_pio_4_external_connection_export>),      //      pid_error_pio_4_external_connection.export
		.pid_error_pio_5_external_connection_export      (<connected-to-pid_error_pio_5_external_connection_export>),      //      pid_error_pio_5_external_connection.export
		.pid_error_pio_6_external_connection_export      (<connected-to-pid_error_pio_6_external_connection_export>),      //      pid_error_pio_6_external_connection.export
		.pid_error_pio_7_external_connection_export      (<connected-to-pid_error_pio_7_external_connection_export>),      //      pid_error_pio_7_external_connection.export
		.pid_values_pio_external_connection_export       (<connected-to-pid_values_pio_external_connection_export>),       //       pid_values_pio_external_connection.export
		.pwm_pio_0_external_connection_export            (<connected-to-pwm_pio_0_external_connection_export>),            //            pwm_pio_0_external_connection.export
		.pwm_pio_1_external_connection_export            (<connected-to-pwm_pio_1_external_connection_export>),            //            pwm_pio_1_external_connection.export
		.pwm_pio_2_external_connection_export            (<connected-to-pwm_pio_2_external_connection_export>),            //            pwm_pio_2_external_connection.export
		.pwm_pio_3_external_connection_export            (<connected-to-pwm_pio_3_external_connection_export>),            //            pwm_pio_3_external_connection.export
		.pwm_pio_4_external_connection_export            (<connected-to-pwm_pio_4_external_connection_export>),            //            pwm_pio_4_external_connection.export
		.pwm_pio_5_external_connection_export            (<connected-to-pwm_pio_5_external_connection_export>),            //            pwm_pio_5_external_connection.export
		.pwm_pio_6_external_connection_export            (<connected-to-pwm_pio_6_external_connection_export>),            //            pwm_pio_6_external_connection.export
		.pwm_pio_7_external_connection_export            (<connected-to-pwm_pio_7_external_connection_export>),            //            pwm_pio_7_external_connection.export
		.quad_pio_0_external_connection_export           (<connected-to-quad_pio_0_external_connection_export>),           //           quad_pio_0_external_connection.export
		.quad_pio_10_external_connection_export          (<connected-to-quad_pio_10_external_connection_export>),          //          quad_pio_10_external_connection.export
		.quad_pio_11_external_connection_export          (<connected-to-quad_pio_11_external_connection_export>),          //          quad_pio_11_external_connection.export
		.quad_pio_1_external_connection_export           (<connected-to-quad_pio_1_external_connection_export>),           //           quad_pio_1_external_connection.export
		.quad_pio_2_external_connection_export           (<connected-to-quad_pio_2_external_connection_export>),           //           quad_pio_2_external_connection.export
		.quad_pio_3_external_connection_export           (<connected-to-quad_pio_3_external_connection_export>),           //           quad_pio_3_external_connection.export
		.quad_pio_4_external_connection_export           (<connected-to-quad_pio_4_external_connection_export>),           //           quad_pio_4_external_connection.export
		.quad_pio_5_external_connection_export           (<connected-to-quad_pio_5_external_connection_export>),           //           quad_pio_5_external_connection.export
		.quad_pio_6_external_connection_export           (<connected-to-quad_pio_6_external_connection_export>),           //           quad_pio_6_external_connection.export
		.quad_pio_7_external_connection_export           (<connected-to-quad_pio_7_external_connection_export>),           //           quad_pio_7_external_connection.export
		.quad_pio_8_external_connection_export           (<connected-to-quad_pio_8_external_connection_export>),           //           quad_pio_8_external_connection.export
		.quad_pio_9_external_connection_export           (<connected-to-quad_pio_9_external_connection_export>),           //           quad_pio_9_external_connection.export
		.quad_reset_pio_external_connection_export       (<connected-to-quad_reset_pio_external_connection_export>),       //       quad_reset_pio_external_connection.export
		.reset_reset_n                                   (<connected-to-reset_reset_n>)                                    //                                    reset.reset_n
	);

