-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/I_component.vhd
-- Created: 2012-04-20 16:35:20
-- 
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: I_component
-- Source Path: fil_pid/Controller/I_component
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY I_component IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        Out1                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En42
        );
END I_component;


ARCHITECTURE rtl OF I_component IS

  -- Signals
  SIGNAL In1_signed                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Gain_2_mul_temp                  : signed(47 DOWNTO 0);  -- sfix48_En54
  SIGNAL Gain_2_out1                      : signed(31 DOWNTO 0);  -- sfix32_En40
  SIGNAL Sum1_out1                        : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Unit_Delay_1_out1                : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Sum1_add_cast                    : signed(44 DOWNTO 0);  -- sfix45_En40
  SIGNAL Sum1_add_cast_1                  : signed(44 DOWNTO 0);  -- sfix45_En40
  SIGNAL Sum1_add_temp                    : signed(44 DOWNTO 0);  -- sfix45_En40
  SIGNAL Gain_4_mul_temp                  : signed(47 DOWNTO 0);  -- sfix48_En57
  SIGNAL Gain_4_out1                      : signed(31 DOWNTO 0);  -- sfix32_En42

BEGIN
  In1_signed <= signed(In1);

  Gain_2_mul_temp <= to_signed(27488, 16) * In1_signed;
  Gain_2_out1 <= Gain_2_mul_temp(45 DOWNTO 14);

  Unit_Delay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_1_out1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_1_out1 <= Sum1_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_1_process;


  Sum1_add_cast <= resize(Gain_2_out1, 45);
  Sum1_add_cast_1 <= resize(Unit_Delay_1_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 45);
  Sum1_add_temp <= Sum1_add_cast + Sum1_add_cast_1;
  Sum1_out1 <= Sum1_add_temp(43 DOWNTO 12);

  Gain_4_mul_temp <= to_signed(26844, 16) * Sum1_out1;
  Gain_4_out1 <= Gain_4_mul_temp(46 DOWNTO 15);

  Out1 <= std_logic_vector(Gain_4_out1);

END rtl;

