-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/D_component.vhd
-- Created: 2012-04-20 16:35:20
-- 
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: D_component
-- Source Path: fil_pid/Controller/D_component
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY D_component IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        Out1                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En33
        );
END D_component;


ARCHITECTURE rtl OF D_component IS

  -- Signals
  SIGNAL In1_signed                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Gain_3_mul_temp                  : signed(47 DOWNTO 0);  -- sfix48_En52
  SIGNAL Gain_3_out1                      : signed(31 DOWNTO 0);  -- sfix32_En38
  SIGNAL Unit_Delay_2_out1                : signed(31 DOWNTO 0);  -- sfix32_En38
  SIGNAL Sum2_sub_cast                    : signed(32 DOWNTO 0);  -- sfix33_En38
  SIGNAL Sum2_sub_cast_1                  : signed(32 DOWNTO 0);  -- sfix33_En38
  SIGNAL Sum2_sub_temp                    : signed(32 DOWNTO 0);  -- sfix33_En38
  SIGNAL Sum2_out1                        : signed(31 DOWNTO 0);  -- sfix32_En48
  SIGNAL Gain_5_mul_temp                  : signed(47 DOWNTO 0);  -- sfix48_En48
  SIGNAL Gain_5_out1                      : signed(31 DOWNTO 0);  -- sfix32_En33

BEGIN
  In1_signed <= signed(In1);

  Gain_3_mul_temp <= to_signed(20616, 16) * In1_signed;
  Gain_3_out1 <= Gain_3_mul_temp(45 DOWNTO 14);

  Unit_Delay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_2_out1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_2_out1 <= Gain_3_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_2_process;


  Sum2_sub_cast <= resize(Gain_3_out1, 33);
  Sum2_sub_cast_1 <= resize(Unit_Delay_2_out1, 33);
  Sum2_sub_temp <= Sum2_sub_cast - Sum2_sub_cast_1;
  Sum2_out1 <= Sum2_sub_temp(21 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';

  Gain_5_mul_temp <= to_signed(20000, 16) * Sum2_out1;
  Gain_5_out1 <= Gain_5_mul_temp(46 DOWNTO 15);

  Out1 <= std_logic_vector(Gain_5_out1);

END rtl;

